apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: Ollama
metadata:
  name: ollama
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  namespace: ollama
  values:
    ollama:
      models:
        pull:
        - llama3.2
